// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    databaseURL:
        "https://interviewassignment-39d95-default-rtdb.asia-southeast1.firebasedatabase.app",
    apiKey: 'AIzaSyCKsda8_gtmZ0JODQnw7hjlld9PLl_vYns',
    appId: '1:212758876308:web:a4e4e3aeb70c297d27e481',
    messagingSenderId: '212758876308',
    projectId: 'interviewassignment-39d95',
    authDomain: 'interviewassignment-39d95.firebaseapp.com',
    storageBucket: 'interviewassignment-39d95.appspot.com',
    measurementId: 'G-9TTQW1H4WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL:
        "https://interviewassignment-39d95-default-rtdb.asia-southeast1.firebasedatabase.app",
    apiKey: 'AIzaSyBxusOTKxw0palP_psHTmoOt9C5sTSMlCg',
    appId: '1:212758876308:android:3ff7ec42a16ac1d327e481',
    messagingSenderId: '212758876308',
    projectId: 'interviewassignment-39d95',
    storageBucket: 'interviewassignment-39d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    databaseURL:
        "https://interviewassignment-39d95-default-rtdb.asia-southeast1.firebasedatabase.app",
    apiKey: 'AIzaSyA4TNsKpwoiOOvEBWzKkZPufpsGxVyLoI8',
    appId: '1:212758876308:ios:e901d6467f46471427e481',
    messagingSenderId: '212758876308',
    projectId: 'interviewassignment-39d95',
    storageBucket: 'interviewassignment-39d95.appspot.com',
    iosClientId:
        '212758876308-86j6spg0pcimcoft2lc00bl5f0uiiat7.apps.googleusercontent.com',
    iosBundleId: 'com.example.internshipAssignment',
  );
}
